### ISSUE TITLE
The sleep method is bad

### ISSUE THREAD

**Issue by ZanderBrown** [Hopson97/Sort-Algorithm-Visualiser#2]
It does of course block the main thread, Ideally [Timer](https://docs.oracle.com/javase/7/docs/api/javax/swing/Timer.html) would be used

**Comment by SalmonSan** [comment]
The sleep method is good, the fuck u talking about?

**Comment by Hopson97** [comment]
@SalmonSan watch your language man

@ZanderBrown Can you you elaborate a bit more please?  It works fine, so I don't see the issue

**Comment by ZanderBrown** [comment]
It blocks the main thread from doing anything which Is Bad™ because swing can't process events

Ideally either a timer would be used or the sorting would happen in a separate thread and use the standard Thread.sleep() method

Unfortunatly either way will be awkward

**Comment by SalmonSan** [comment]
@ZanderBrown Plus, I don't think there can be wrong stuff in coding. It's important if the code works, not the way it works.

**Comment by SalmonSan** [comment]
You can make it work in 100 lines, or in 2

**Comment by ZanderBrown** [comment]
@SalmonSan sarcasm? *\*Please be sarcasm\**

**Comment by SalmonSan** [comment]
Complexity doesn't matter, as long as it works properly.

**Comment by Hopson97** [comment]
Ahh @ZanderBrown makes sense, thanks for info! :) I'll see what I can do

**Comment by Hopson97** [comment]
Thread.sleep worked

**Comment by Hopson97** [comment]
https://stackoverflow.com/questions/14106953/swing-thread-sleep-stop-jtextfield-settext-working

**Comment by Hopson97** [comment]
I mean Thread.sleep still blocks Swing from doing events, but I am not using anything Swing except for canvas while the algorithms are running. (Eg, that SO questions refers to JTextField not working, but I don't have any GUI)

 Is it still an issue?

**Comment by ZanderBrown** [comment]
Technically yes, the WM can send an event to a window at any time and expects a response quickly or they may assume it's not responding (because well it isn't)

**Comment by Hopson97** [comment]
If you mean shutting the window while it is running, I am yet  to run into issues with this

**Comment by ZanderBrown** [comment]
Destroy is an example yes

So far you just getting lucky that delay + algorithm run is quite short, on low-end machines ext it'll be more noticeable

**Comment by Hopson97** [comment]
I now use a swing worker to execute the sorting algorithms, seems to have fixed the issue and no longer runs on the EDT :)

**Comment by Hopson97** [comment]
Ngl the code is nasty for now, but I am working on it
