### ISSUE TITLE
gradle wrapper

### ISSUE THREAD

**Issue by Wabri** [Hopson97/Sort-Algorithm-Visualiser#4]
Maybe can be usefull a gradle wrapper, it is always raccomended. If you want more info you can see here: [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html)

**Comment by immackay** [comment]
This isn't necessary; if the IDE doesn't have a bundled gradle wrapper, then users can download one or install the binaries. It can be easier though.

**Comment by Wabri** [comment]
reasonable
